= Changelog

This document provides information about changes that have been made for each new version
of the Signature Service Support Library.

== Version 2401.1

=== New features
* Support for using text template for visible signatures.
* Support for specifying signature attributes per document when signing multiple documents at the same time.
* Support for reading visible signature logo image to use from signature attributes.

=== Improvements and bug fixes
* Improvements in `V2SupportServiceAPI.Builder` to give better errors if required configuration is missing.

=== Upgrade notes
This release contains no breaking changes. This section contains brie information about the
included enhancements.

==== Visible signature text template
By using visible signature text template it is possible to get full control over the text
that is presented within the visible signatures. Information and examples on how to use
this feature is available in README.

==== Signature attributes per document
New overloaded version of the method `prepareSignature(...)` has been added to the SupportServiceAPI interface
that takes an additional map-parameter `Map<String, List<Attribute>> documentSignatureAttributes`. Map-key is a document reference ID which is mapped to the list of signature attributes that should be used for
that particular document.

== Version 2312.1

=== New features
* Added support for LTA-level signatures with customizable time stamp source.

=== Improvements and bug fixes
* Fixed incorrect object reference in XAdES DataObjectFormat-element that caused warning during validation.

=== Vulnerability mitigations
* xmlsec upgraded to 2.3.4 (CVE-2023-44483)
* json upgraded to 20231013 (CVE-2023-5072)

=== Upgrade notes
A new class TimeStampConfig has been added that contains information about time stamp configuration.
An instance of this class must be provided to the SupportAPIProfile builder in order to customize time stamping
when using signature levels that includes timestamps (-T, LT and -LTA).

== Version 2308.1
This is the first publicly available version of the Signature Support Service Library. The main purpose
of the library is to help with creating signature requests, and processing signature responses, according
to the technical framework specified by Sweden Connect (https://docs.swedenconnect.se/technical-framework/).