/************************************************************************
 *                                                                       *
 *  Signature Service - Support Service Library                          *
 *                                                                       *
 *  This software is free software; you can redistribute it and/or       *
 *  modify it under the terms of the GNU Lesser General Public License   *
 *  License as published by the Free Software Foundation; either         *
 *  version 3 of the License, or any later version.                      *
 *                                                                       *
 *  See terms of license at gnu.org.                                     *
 *                                                                       *
 *************************************************************************/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.23 at 04:03:45 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "v2.api.support.signatureservice.se",
xmlns = {   
		@javax.xml.bind.annotation.XmlNs(namespaceURI = "v2.api.support.signatureservice.se", prefix = "api")},
	    elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package se.signatureservice.support.api.v2;
